### PR TITLE
fix package, add hut4 rules file

### PR DESCRIPTION
**Pull request by codegoblin**
this silos the hut4 rules into a single file

### CODE REVIEW

**Comment by cdidyk** [comment]
I'm not sure what came of the discussion on slack, but it sounds like it makes more sense to leave the bletchley-level linter/styles "pristine" (instead of forcing hut4's modifications on it) and keeping hut-specific modifications separate. I'm guessing that would happen through hut-specific packages?

Also, what do you think about describing the process for modifying hut-specific (and bletchley-wide) style guides in the wiki?

**Comment by cdidyk** [comment]
Oh, I forgot to say that I +1 this PR. Even if the answers to my questions above change some things, I don't think those changes would be a big deal nor should they stand in the way of us getting going customizing this guide.

**Comment by codegoblin** [comment]
You don't have to build a new package, you just need to stipulate `extend: bletchley/hut4` ... if you just want all the top-level, non-hut rules you would stipulate `extend: bletchley` in the .eslintrc

I totally agree with the readme expansion. Maybe I'll get some time to do that today.

**Comment by cdidyk** [comment]
Groovy

**Pull request merged**
